name: pygmt-dev-testing
channels:
    - conda-forge
    - defaults
dependencies:
    # Required dependencies
    - pip
    - numpy>=1.19
    - pandas
    - xarray
    - netCDF4
    - packaging
    # Optional dependencies
    - geopandas
    # Development dependencies
    - black
    - blackdoc
    - docformatter
    - dvc
    - flake8
    - ghostscript
    - ipython
    - isort>=5
    - jupyter
    - make
    - matplotlib
    - myst-parser
    - pylint
    - pytest-cov
    - pytest-mpl
    - pytest>=6.0
    - sphinx
    - sphinx-copybutton
    - sphinx-gallery
    - sphinx_rtd_theme
